---
abstract: 'Tiny asynchronous (non-blocking) interface to EC2 using AnyEvent'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-EC2-Tiny
no_index:
  file:
    - README.pod
resources:
  bugtracker: http://github.com/xsawyerx/anyevent-ec2-tiny/issues
  repository: http://github.com/xsawyerx/anyevent-ec2-tiny
version: 0.001
